# Generated by Django 5.0.3 on 2024-06-28 18:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CiePesq',
            fields=[
                ('id_CiePesq', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_componente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Constelacao',
            fields=[
                ('id_constelacao', models.AutoField(primary_key=True, serialize=False)),
                ('const_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Galaxia',
            fields=[
                ('id_galaxia', models.AutoField(primary_key=True, serialize=False)),
                ('galax_desc', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PlanetaTipo',
            fields=[
                ('id_planetTipo', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGalax',
            fields=[
                ('id_tipoGalax', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipoGalax', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CatTempCor',
            fields=[
                ('id_CatCorTemp', models.AutoField(primary_key=True, serialize=False)),
                ('tempK_ini', models.IntegerField()),
                ('tempK_fim', models.IntegerField()),
                ('CCT_corCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Corpo',
            fields=[
                ('cod_corpo', models.AutoField(primary_key=True, serialize=False)),
                ('dta_descoberta', models.IntegerField(blank=True, null=True)),
                ('corpo_CiePesq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ciepesq')),
            ],
        ),
        migrations.CreateModel(
            name='Estrela',
            fields=[
                ('id_estrela', models.AutoField(primary_key=True, serialize=False)),
                ('estr_nome', models.CharField(blank=True, max_length=45, null=True)),
                ('estrela_id_catCor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cattempcor')),
                ('estrela_id_constelacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.constelacao')),
                ('estrela_tb_corpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corpo')),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id_planeta', models.AutoField(primary_key=True, serialize=False)),
                ('desc_planeta', models.CharField(max_length=100)),
                ('vel_orb_kms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diam_equatorial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_rotacao', models.FloatField()),
                ('gravidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_codCorpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corpo')),
                ('plan_planetaTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planetatipo')),
            ],
        ),
        migrations.CreateModel(
            name='SatNatural',
            fields=[
                ('cod_satNat', models.AutoField(primary_key=True, serialize=False)),
                ('satNat_nome', models.CharField(max_length=100)),
                ('satNat_corpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corpo')),
                ('satNat_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.planeta')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('desc_sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('sist_estrPrincipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estrela')),
                ('sist_galax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.galaxia')),
            ],
        ),
        migrations.AddField(
            model_name='planeta',
            name='plan_id_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sistema'),
        ),
        migrations.CreateModel(
            name='EstrPeriferica',
            fields=[
                ('id_estrPeriferica', models.AutoField(primary_key=True, serialize=False)),
                ('estrPeriferica_id_estrela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estrela')),
                ('estrPeriferica_id_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sistema')),
            ],
        ),
        migrations.AddField(
            model_name='galaxia',
            name='galax_tipoGalax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipogalax'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('groups', models.ManyToManyField(blank=True, related_name='app_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='app_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompAtmosfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_componente', models.FloatField()),
                ('compo_id_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.componente')),
                ('compo_cod_corpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corpo')),
            ],
            options={
                'unique_together': {('compo_id_componente', 'compo_cod_corpo')},
            },
        ),
    ]
