# Generated by Django 5.0.3 on 2024-06-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciepesq',
            name='email',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='ciepesq',
            name='instituicao',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='ciepesq',
            name='nome',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='ciepesq',
            name='senha',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
